version: '3'

services:
  backend:
    build: ./back-end
    ports:
      - "5253:5252"
    volumes:
      - ./back-end:/app

  frontend:
    build: ./front-end
    ports:
      - "9002:9000"
    volumes:
      - ./front-end:/usr/share/nginx/html

