version: '3'

services:
  backend:
    build: ./back-end
    volumes:
      - ./back-end:/app

  backend_2:
    build: ./back-end
    volumes:
      - ./back-end:/app

  frontend:
    build: ./front-end
    volumes:
      - ./front-end:/usr/share/nginx/html

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - backend_2

